#!/bin/sh
COMMIT_MSG_FILE=$1

# Получаем название текущей ветки
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Извлекаем номер задачи из ветки
BRANCH_NUMBER=$(echo "$BRANCH_NAME" | grep -o '[0-9]\+')

if [ ! -z "$BRANCH_NUMBER" ]; then
  COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

  # Если в начале сообщения еще нет номера задачи, добавляем его
  # Формат станет: "feat: 1 - описание"
  if ! echo "$COMMIT_MSG" | grep -q "$BRANCH_NUMBER"; then
    MODIFIED_MSG=$(echo "$COMMIT_MSG" | sed "s/^\([a-z]\+\): /\1: $BRANCH_NUMBER - /")
    echo "$MODIFIED_MSG" > "$COMMIT_MSG_FILE"
  else
    MODIFIED_MSG=$COMMIT_MSG
  fi

  # Валидация итогового формата
  COMMIT_REGEX="^(feat|fix|refactor|docs|chore|test): [0-9]{1,5} \-( [a-zA-Z_'&:.-]+){2,}$"

  if ! echo "$MODIFIED_MSG" | grep -Eq "$COMMIT_REGEX"; then
    echo "--------------------------------------------------------"
    echo "❌ ERROR: Invalid commit message format."
    echo "Expected: <type>: <task_number> - <description>"
    echo "Example: feat: 1 - add login button"
    echo "--------------------------------------------------------"
    exit 1
  fi

  echo "✅ Commit message style is valid!"
fi